Programming for Data Science: Final Project 
Name: Letizia 
Surname: Lanza 
ID: VR502321

PART 1: Data Exploration and Data Wrangling 

1. Explore the dataset: your first task is to explore the data as seen in class, finding correlations between attributes and finding some interesting aspects that justify the next parts of the analysis. 

The chosen dataset is available at the following Kaggle's link: https://www.kaggle.com/datasets/sogun3/uspollution 
The dataset is about pollution in the U.S. that has been well documented by the U.S. EPA. 
In particular, this dataset deal with the four major pollutants, which are Nitrogen Dioxide (NO2), Sulphur Dioxide (SO2), Carbon Monoxide (CO) and Ozone (O3), for every day between 2000 and 2016.

The first thing to succesfully carry out this and the following exercises, is to import some libraries as we have seen during the lessons such as: 

In [2]:
import os 
import numpy as np 
import pandas as pd 

The aim of the following command is being able to read data from a CSV file and load it into a Pandas DataFrame.

In [3]:
pollution_df = pd.read_csv('pollution_us_2000_2016.csv')
pollution_df

Unnamed: 0  State Code  County Code  Site Num  \
0                 0           4           13      3002   
1                 1           4           13      3002   
2                 2           4           13      3002   
3                 3           4           13      3002   
4                 4           4           13      3002   
...             ...         ...          ...       ...   
1746656       24599          56           21       100   
1746657       24600          56           21       100   
1746658       24601          56           21       100   
1746659       24602          56           21       100   
1746660       24603          56           21       100   

                                         Address    State    County  \
0        1645 E ROOSEVELT ST-CENTRAL PHOENIX STN  Arizona  Maricopa   
1        1645 E ROOSEVELT ST-CENTRAL PHOENIX STN  Arizona  Maricopa   
2        1645 E ROOSEVELT ST-CENTRAL PHOENIX STN  Arizona  Maricopa   
3        1645 E ROOSEVELT ST-CENTRAL PHOENIX STN  Arizona  Maricopa   
4        1645 E ROOSEVELT ST-CENTRAL PHOENIX STN  Arizona  Maricopa   
...                                          ...      ...       ...   
1746656    NCore - North Cheyenne Soccer Complex  Wyoming   Laramie   
1746657    NCore - North Cheyenne Soccer Complex  Wyoming   Laramie   
1746658    NCore - North Cheyenne Soccer Complex  Wyoming   Laramie   
1746659    NCore - North Cheyenne Soccer Complex  Wyoming   Laramie   
1746660    NCore - North Cheyenne Soccer Complex  Wyoming   Laramie   

                  City  Date Local          NO2 Units  ...          SO2 Units  \
0              Phoenix  2000-01-01  Parts per billion  ...  Parts per billion   
1              Phoenix  2000-01-01  Parts per billion  ...  Parts per billion   
2              Phoenix  2000-01-01  Parts per billion  ...  Parts per billion   
3              Phoenix  2000-01-01  Parts per billion  ...  Parts per billion   
4              Phoenix  2000-01-02  Parts per billion  ...  Parts per billion   
...                ...         ...                ...  ...                ...   
1746656  Not in a city  2016-03-30  Parts per billion  ...  Parts per billion   
1746657  Not in a city  2016-03-31  Parts per billion  ...  Parts per billion   
1746658  Not in a city  2016-03-31  Parts per billion  ...  Parts per billion   
1746659  Not in a city  2016-03-31  Parts per billion  ...  Parts per billion   
1746660  Not in a city  2016-03-31  Parts per billion  ...  Parts per billion   

         SO2 Mean  SO2 1st Max Value  SO2 1st Max Hour SO2 AQI  \
0        3.000000                9.0                21    13.0   
1        3.000000                9.0                21    13.0   
2        2.975000                6.6                23     NaN   
3        2.975000                6.6                23     NaN   
4        1.958333                3.0                22     4.0   
...           ...                ...               ...     ...   
1746656  0.000000                0.0                 2     NaN   
1746657 -0.022727                0.0                 0     0.0   
1746658 -0.022727                0.0                 0     0.0   
1746659  0.000000                0.0                 5     NaN   
1746660  0.000000                0.0                 5     NaN   

                  CO Units   CO Mean  CO 1st Max Value  CO 1st Max Hour CO AQI  
0        Parts per million  1.145833             4.200               21    NaN  
1        Parts per million  0.878947             2.200               23   25.0  
2        Parts per million  1.145833             4.200               21    NaN  
3        Parts per million  0.878947             2.200               23   25.0  
4        Parts per million  0.850000             1.600               23    NaN  
...                    ...       ...               ...              ...    ...  
1746656  Parts per million  0.091667             0.100                2    1.0  
1746657  Parts per million  0.067714         

As it can be seen the dataset has 1.746.661 rows and 29 columns. 

The following DataFrame.drop() function is used to remove rows or columns that are not useful in the DataFrame. 

In [4]:
pollution_df = pollution_df.drop(['Unnamed: 0','State Code','County Code','Site Num','Address','NO2 Units','O3 Units','SO2 Units','CO Units'], axis = 1)
pollution_df

State    County           City  Date Local   NO2 Mean  \
0        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
1        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
2        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
3        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
4        Arizona  Maricopa        Phoenix  2000-01-02  22.958333   
...          ...       ...            ...         ...        ...   
1746656  Wyoming   Laramie  Not in a city  2016-03-30   1.083333   
1746657  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   
1746658  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   
1746659  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   
1746660  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   

         NO2 1st Max Value  NO2 1st Max Hour  NO2 AQI   O3 Mean  \
0                     49.0                19       46  0.022500   
1                     49.0                19       46  0.022500   
2                     49.0                19       46  0.022500   
3                     49.0                19       46  0.022500   
4                     36.0                19       34  0.013375   
...                    ...               ...      ...       ...   
1746656                1.6                 9        1  0.043917   
1746657                1.3                 5        1  0.045263   
1746658                1.3                 5        1  0.045263   
1746659                1.3                 5        1  0.045263   
1746660                1.3                 5        1  0.045263   

         O3 1st Max Value  O3 1st Max Hour  O3 AQI  SO2 Mean  \
0                   0.040               10      34  3.000000   
1                   0.040               10      34  3.000000   
2                   0.040               10      34  2.975000   
3                   0.040               10      34  2.975000   
4                   0.032               10      27  1.958333   
...                   ...              ...     ...       ...   
1746656             0.048               18      44  0.000000   
1746657             0.047                9      44 -0.022727   
1746658             0.047                9      44 -0.022727   
1746659             0.047                9      44  0.000000   
1746660             0.047                9      44  0.000000   

         SO2 1st Max Value  SO2 1st Max Hour  SO2 AQI   CO Mean  \
0                      9.0                21     13.0  1.145833   
1                      9.0                21     13.0  0.878947   
2                      6.6                23      NaN  1.145833   
3                      6.6                23      NaN  0.878947   
4                      3.0                22      4.0  0.850000   
...                    ...               ...      ...       ...   
1746656                0.0                 2      NaN  0.091667   
1746657                0.0                 0      0.0  0.067714   
1746658                0.0                 0      0.0  0.100000   
1746659                0.0                 5      NaN  0.067714   
1746660                0.0                 5      NaN  0.100000   

         CO 1st Max Value  CO 1st Max Hour  CO AQI  
0                   4.200               21     NaN  
1                   2.200               23    25.0  
2                   4.200               21     NaN  
3                   2.200               23    25.0  
4                   1.600               23     NaN  
...                   ...              ...     ...  
1746656             0.100                2     1.0  
1746657             0.127                0     NaN  
1746658             0.100                0     1.0  
1746659             0.127                0     NaN  
1746660             0.100                0     1.0  

[1746661 rows x 20 columns]

The number of columns decreased from 29 to 20 as it is required to delete Unnamed: 0 column, State Code column, County Code column, Site Num column, Address column, NO2 Units column, O3 Units column, SO2 Units column and CO Units column.

The DataFrame.info() function prints information about the DataFrame such as number of columns, column labels, column data types, memory usage, range index and the number of cells in each column (non-null values): 

In [5]:
pollution_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1746661 entries, 0 to 1746660
Data columns (total 20 columns):
 #   Column             Dtype  
---  ------             -----  
 0   State              object 
 1   County             object 
 2   City               object 
 3   Date Local         object 
 4   NO2 Mean           float64
 5   NO2 1st Max Value  float64
 6   NO2 1st Max Hour   int64  
 7   NO2 AQI            int64  
 8   O3 Mean            float64
 9   O3 1st Max Value   float64
 10  O3 1st Max Hour    int64  
 11  O3 AQI             int64  
 12  SO2 Mean           float64
 13  SO2 1st Max Value  float64
 14  SO2 1st Max Hour   int64  
 15  SO2 AQI            float64
 16  CO Mean            float64
 17  CO 1st Max Value   float64
 18  CO 1st Max Hour    int64  
 19  CO AQI             float64
dtypes: float64(10), int64(6), object(4)
memory usage: 266.5+ MB


As it can be seen there are 20 column with a RangeIndex (rows) for a total of 1.746.661. 
There are also 3 types of data type such as object (generic data), float (real numbers that can have a fractional part) and int (real whole numbers without a fractional part).
Another information that can be read is the memory usage of 266.5+ MB. 

The DataFrame.describe() function gives descriptive information about the dataset as it can be seen below: 

In [6]:
pollution_df.describe()

NO2 Mean  NO2 1st Max Value  NO2 1st Max Hour       NO2 AQI  \
count  1.746661e+06       1.746661e+06      1.746661e+06  1.746661e+06   
mean   1.282193e+01       2.541485e+01      1.173102e+01  2.389822e+01   
std    9.504814e+00       1.599963e+01      7.877501e+00  1.516280e+01   
min   -2.000000e+00      -2.000000e+00      0.000000e+00  0.000000e+00   
25%    5.750000e+00       1.300000e+01      5.000000e+00  1.200000e+01   
50%    1.073913e+01       2.400000e+01      9.000000e+00  2.300000e+01   
75%    1.771364e+01       3.570000e+01      2.000000e+01  3.300000e+01   
max    1.395417e+02       2.670000e+02      2.300000e+01  1.320000e+02   

            O3 Mean  O3 1st Max Value  O3 1st Max Hour        O3 AQI  \
count  1.746661e+06      1.746661e+06     1.746661e+06  1.746661e+06   
mean   2.612485e-02      3.920331e-02     1.017053e+01  3.605012e+01   
std    1.136974e-02      1.534362e-02     4.003144e+00  1.978042e+01   
min    0.000000e+00      0.000000e+00     0.000000e+00  0.000000e+00   
25%    1.787500e-02      2.900000e-02     9.000000e+00  2.500000e+01   
50%    2.587500e-02      3.800000e-02     1.000000e+01  3.300000e+01   
75%    3.391700e-02      4.800000e-02     1.100000e+01  4.200000e+01   
max    9.508300e-02      1.410000e-01     2.300000e+01  2.180000e+02   

           SO2 Mean  SO2 1st Max Value  SO2 1st Max Hour        SO2 AQI  \
count  1.746661e+06       1.746661e+06      1.746661e+06  873754.000000   
mean   1.870364e+00       4.492185e+00      9.664906e+00       7.115945   
std    2.760435e+00       7.679866e+00      6.731228e+00      11.937473   
min   -2.000000e+00      -2.000000e+00      0.000000e+00       0.000000   
25%    2.565220e-01       8.000000e-01      5.000000e+00       1.000000   
50%    9.875000e-01       2.000000e+00      8.000000e+00       3.000000   
75%    2.325000e+00       5.000000e+00      1.400000e+01       9.000000   
max    3.216250e+02       3.510000e+02      2.300000e+01     200.000000   

            CO Mean  CO 1st Max Value  CO 1st Max Hour         CO AQI  
count  1.746661e+06      1.746661e+06     1.746661e+06  873338.000000  
mean   3.682177e-01      6.201067e-01     7.875026e+00       5.996595  
std    3.140231e-01      6.439361e-01     7.978844e+00       5.851836  
min   -4.375000e-01     -4.000000e-01     0.000000e+00       0.000000  
25%    1.834580e-01      2.920000e-01     0.000000e+00       2.000000  
50%    2.926250e-01      4.000000e-01     6.000000e+00       5.000000  
75%    4.666670e-01      8.000000e-01     1.300000e+01       8.000000  
max    7.508333e+00      1.990000e+01     2.300000e+01     201.000000

Glossary: 
- count: the number of non - null values in each column 
- mean: the mean (average) value of each numerical column 
- sdt: the standard deviation of each numerical column 
- min: the minimum value in each numerical column 
- 25%: the value at the 25th percentile (first quartile) of each numerical column 
- 50%: the value at the 50th percentile (median or second quartile) of each numerical column 
- 75%: the value at the 75th percentile (third quartile) of each numerical column
- max: the maximum value in each numerical column 

The DataFrame.describe().T function is used to transpose index and columns of the data frame as follow: 

In [7]:
pollution_df.describe().T

count       mean        std     min        25%  \
NO2 Mean           1746661.0  12.821930   9.504814 -2.0000   5.750000   
NO2 1st Max Value  1746661.0  25.414848  15.999630 -2.0000  13.000000   
NO2 1st Max Hour   1746661.0  11.731023   7.877501  0.0000   5.000000   
NO2 AQI            1746661.0  23.898217  15.162805  0.0000  12.000000   
O3 Mean            1746661.0   0.026125   0.011370  0.0000   0.017875   
O3 1st Max Value   1746661.0   0.039203   0.015344  0.0000   0.029000   
O3 1st Max Hour    1746661.0  10.170529   4.003144  0.0000   9.000000   
O3 AQI             1746661.0  36.050121  19.780423  0.0000  25.000000   
SO2 Mean           1746661.0   1.870364   2.760435 -2.0000   0.256522   
SO2 1st Max Value  1746661.0   4.492185   7.679866 -2.0000   0.800000   
SO2 1st Max Hour   1746661.0   9.664906   6.731228  0.0000   5.000000   
SO2 AQI             873754.0   7.115945  11.937473  0.0000   1.000000   
CO Mean            1746661.0   0.368218   0.314023 -0.4375   0.183458   
CO 1st Max Value   1746661.0   0.620107   0.643936 -0.4000   0.292000   
CO 1st Max Hour    1746661.0   7.875026   7.978844  0.0000   0.000000   
CO AQI              873338.0   5.996595   5.851836  0.0000   2.000000   

                         50%        75%         max  
NO2 Mean           10.739130  17.713636  139.541667  
NO2 1st Max Value  24.000000  35.700000  267.000000  
NO2 1st Max Hour    9.000000  20.000000   23.000000  
NO2 AQI            23.000000  33.000000  132.000000  
O3 Mean             0.025875   0.033917    0.095083  
O3 1st Max Value    0.038000   0.048000    0.141000  
O3 1st Max Hour    10.000000  11.000000   23.000000  
O3 AQI             33.000000  42.000000  218.000000  
SO2 Mean            0.987500   2.325000  321.625000  
SO2 1st Max Value   2.000000   5.000000  351.000000  
SO2 1st Max Hour    8.000000  14.000000   23.000000  
SO2 AQI             3.000000   9.000000  200.000000  
CO Mean             0.292625   0.466667    7.508333  
CO 1st Max Value    0.400000   0.800000   19.900000  
CO 1st Max Hour     6.000000  13.000000   23.000000  
CO AQI              5.000000   8.000000  201.000000

The DataFrame.head() function displays the first 5 rows of the DataFrame by default as below: 

In [8]:
pollution_df.head()

State    County     City  Date Local   NO2 Mean  NO2 1st Max Value  \
0  Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
1  Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
2  Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
3  Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
4  Arizona  Maricopa  Phoenix  2000-01-02  22.958333               36.0   

   NO2 1st Max Hour  NO2 AQI   O3 Mean  O3 1st Max Value  O3 1st Max Hour  \
0                19       46  0.022500             0.040               10   
1                19       46  0.022500             0.040               10   
2                19       46  0.022500             0.040               10   
3                19       46  0.022500             0.040               10   
4                19       34  0.013375             0.032               10   

   O3 AQI  SO2 Mean  SO2 1st Max Value  SO2 1st Max Hour  SO2 AQI   CO Mean  \
0      34  3.000000                9.0                21     13.0  1.145833   
1      34  3.000000                9.0                21     13.0  0.878947   
2      34  2.975000                6.6                23      NaN  1.145833   
3      34  2.975000                6.6                23      NaN  0.878947   
4      27  1.958333                3.0                22      4.0  0.850000   

   CO 1st Max Value  CO 1st Max Hour  CO AQI  
0               4.2               21     NaN  
1               2.2               23    25.0  
2               4.2               21     NaN  
3               2.2               23    25.0  
4               1.6               23     NaN

The DataFrame.tail() function returns the last 5 rows of the dataframe by default as can be seen: 

In [9]:
pollution_df.tail()

State   County           City  Date Local  NO2 Mean  \
1746656  Wyoming  Laramie  Not in a city  2016-03-30  1.083333   
1746657  Wyoming  Laramie  Not in a city  2016-03-31  0.939130   
1746658  Wyoming  Laramie  Not in a city  2016-03-31  0.939130   
1746659  Wyoming  Laramie  Not in a city  2016-03-31  0.939130   
1746660  Wyoming  Laramie  Not in a city  2016-03-31  0.939130   

         NO2 1st Max Value  NO2 1st Max Hour  NO2 AQI   O3 Mean  \
1746656                1.6                 9        1  0.043917   
1746657                1.3                 5        1  0.045263   
1746658                1.3                 5        1  0.045263   
1746659                1.3                 5        1  0.045263   
1746660                1.3                 5        1  0.045263   

         O3 1st Max Value  O3 1st Max Hour  O3 AQI  SO2 Mean  \
1746656             0.048               18      44  0.000000   
1746657             0.047                9      44 -0.022727   
1746658             0.047                9      44 -0.022727   
1746659             0.047                9      44  0.000000   
1746660             0.047                9      44  0.000000   

         SO2 1st Max Value  SO2 1st Max Hour  SO2 AQI   CO Mean  \
1746656                0.0                 2      NaN  0.091667   
1746657                0.0                 0      0.0  0.067714   
1746658                0.0                 0      0.0  0.100000   
1746659                0.0                 5      NaN  0.067714   
1746660                0.0                 5      NaN  0.100000   

         CO 1st Max Value  CO 1st Max Hour  CO AQI  
1746656             0.100                2     1.0  
1746657             0.127                0     NaN  
1746658             0.100                0     1.0  
1746659             0.127                0     NaN  
1746660             0.100                0     1.0

The DataFrame.columns function is an attribute that provides access to the column labels of a DataFrame: 

In [10]:
pollution_df.columns

Index(['State', 'County', 'City', 'Date Local', 'NO2 Mean',
       'NO2 1st Max Value', 'NO2 1st Max Hour', 'NO2 AQI', 'O3 Mean',
       'O3 1st Max Value', 'O3 1st Max Hour', 'O3 AQI', 'SO2 Mean',
       'SO2 1st Max Value', 'SO2 1st Max Hour', 'SO2 AQI', 'CO Mean',
       'CO 1st Max Value', 'CO 1st Max Hour', 'CO AQI'],
      dtype='object')

It also can be checked what type the DataFrame is: 

In [11]:
type(pollution_df)

pandas.core.frame.DataFrame

The DataFrame.sample() function return a random sample of items from an axis of object:

In [12]:
pollution_df.sample()

State     County   City  Date Local   NO2 Mean  NO2 1st Max Value  \
1274613  Maryland  Baltimore  Essex  2012-07-13  13.541667               36.0   

         NO2 1st Max Hour  NO2 AQI   O3 Mean  O3 1st Max Value  \
1274613                 7       34  0.038833             0.062   

         O3 1st Max Hour  O3 AQI  SO2 Mean  SO2 1st Max Value  \
1274613               11      58     1.775                9.5   

         SO2 1st Max Hour  SO2 AQI   CO Mean  CO 1st Max Value  \
1274613                19     13.0  0.204167               0.3   

         CO 1st Max Hour  CO AQI  
1274613                8     3.0

The DataFrame.max() function is used to find the maximum value in the DataFrame: 

In [13]:
pollution_df.max()

State                   Wyoming
County                     York
City                       York
Date Local           2016-05-31
NO2 Mean             139.541667
NO2 1st Max Value         267.0
NO2 1st Max Hour             23
NO2 AQI                     132
O3 Mean                0.095083
O3 1st Max Value          0.141
O3 1st Max Hour              23
O3 AQI                      218
SO2 Mean                321.625
SO2 1st Max Value         351.0
SO2 1st Max Hour             23
SO2 AQI                   200.0
CO Mean                7.508333
CO 1st Max Value           19.9
CO 1st Max Hour              23
CO AQI                    201.0
dtype: object

The DataFrame.min() function is used to find the minimum value in the DataFrame: 

In [14]:
pollution_df.min()

State                    Alabama
County                       Ada
City                 Albuquerque
Date Local            2000-01-01
NO2 Mean                    -2.0
NO2 1st Max Value           -2.0
NO2 1st Max Hour               0
NO2 AQI                        0
O3 Mean                      0.0
O3 1st Max Value             0.0
O3 1st Max Hour                0
O3 AQI                         0
SO2 Mean                    -2.0
SO2 1st Max Value           -2.0
SO2 1st Max Hour               0
SO2 AQI                      0.0
CO Mean                  -0.4375
CO 1st Max Value            -0.4
CO 1st Max Hour                0
CO AQI                       0.0
dtype: object

2. Clean up the dataset: this step encompasses the replacement of null values with appropriate data or their outright removal. During this step you are encouraged to modify the data according to the consideration matured during the exploration.

For checking if there are some null values the DataFrame.isnull() function can be used: 

In [15]:
pollution_df.isnull()

State  County   City  Date Local  NO2 Mean  NO2 1st Max Value  \
0        False   False  False       False     False              False   
1        False   False  False       False     False              False   
2        False   False  False       False     False              False   
3        False   False  False       False     False              False   
4        False   False  False       False     False              False   
...        ...     ...    ...         ...       ...                ...   
1746656  False   False  False       False     False              False   
1746657  False   False  False       False     False              False   
1746658  False   False  False       False     False              False   
1746659  False   False  False       False     False              False   
1746660  False   False  False       False     False              False   

         NO2 1st Max Hour  NO2 AQI  O3 Mean  O3 1st Max Value  \
0                   False    False    False             False   
1                   False    False    False             False   
2                   False    False    False             False   
3                   False    False    False             False   
4                   False    False    False             False   
...                   ...      ...      ...               ...   
1746656             False    False    False             False   
1746657             False    False    False             False   
1746658             False    False    False             False   
1746659             False    False    False             False   
1746660             False    False    False             False   

         O3 1st Max Hour  O3 AQI  SO2 Mean  SO2 1st Max Value  \
0                  False   False     False              False   
1                  False   False     False              False   
2                  False   False     False              False   
3                  False   False     False              False   
4                  False   False     False              False   
...                  ...     ...       ...                ...   
1746656            False   False     False              False   
1746657            False   False     False              False   
1746658            False   False     False              False   
1746659            False   False     False              False   
1746660            False   False     False              False   

         SO2 1st Max Hour  SO2 AQI  CO Mean  CO 1st Max Value  \
0                   False    False    False             False   
1                   False    False    False             False   
2                   False     True    False             False   
3                   False     True    False             False   
4                   False    False    False             False   
...                   ...      ...      ...               ...   
1746656             False     True    False             False   
1746657             False    False    False             False   
1746658             False    False    False             False   
1746659             False     True    False             False   
1746660             False     True    False             False   

         CO 1st Max Hour  CO AQI  
0                  False    True  
1                  False   False  
2                  False    True  
3                  False   False  
4                  False    True  
...                  ...     ...  
1746656            False   False  
1746657            False    True  
1746658            False   False  
1746659            False    True  
1746660            False   False  

[1746661 rows x 20 columns]

As it can be seen, some columns present the "True" word that highlight a null value in that position.

Another way to identify how many null values there are in the dataframe is: 

In [16]:
pollution_df.isnull().sum()

State                     0
County                    0
City                      0
Date Local                0
NO2 Mean                  0
NO2 1st Max Value         0
NO2 1st Max Hour          0
NO2 AQI                   0
O3 Mean                   0
O3 1st Max Value          0
O3 1st Max Hour           0
O3 AQI                    0
SO2 Mean                  0
SO2 1st Max Value         0
SO2 1st Max Hour          0
SO2 AQI              872907
CO Mean                   0
CO 1st Max Value          0
CO 1st Max Hour           0
CO AQI               873323
dtype: int64

To understand the completeness of the dataset, it is useful identifying the percentage of null values in those columns that have shown to exhibit such missing values:

In [17]:
print('percentage of SO2 AQI value:', pollution_df['SO2 AQI'].isna().sum()/len(pollution_df) * 100)

print('percentage of CO AQI value:', pollution_df['CO AQI'].isna().sum()/len(pollution_df) * 100)

percentage of SO2 AQI value: 49.975753738132354
percentage of CO AQI value: 49.99957060929396


As it can be seen, the percentage of null values is quite high 

So, with the following code it can be seen that first it is calculated the mean of a specific column and then every missing values in that column is replaced with the mean value of the referring column. 

In [37]:
SO2_AQI = pollution_df['SO2 AQI'].mean()
pollution_df['SO2 AQI'].fillna(SO2_AQI, inplace = True)
SO2_AQI

/var/folders/nt/j3zdw65j5ys5rx0l1vhss5y40000gn/T/ipykernel_1207/1364701639.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pollution_df['SO2 AQI'].fillna(SO2_AQI, inplace = True)


7.1166722006214735

Moreover, with the following code it can be seen that first it is calculated the mode of a specific column and then every missing values in that column is replaced with the mode value of the referring column. 

In [20]:
CO_AQI = pollution_df['CO AQI'].mode()
pollution_df['CO AQI'].fillna(CO_AQI, inplace = True)
CO_AQI

/var/folders/nt/j3zdw65j5ys5rx0l1vhss5y40000gn/T/ipykernel_1207/1391719805.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  pollution_df['CO AQI'].fillna(CO_AQI, inplace = True)


0    3.0
Name: CO AQI, dtype: float64

Another way to deal with null values can be deleting the columns with that kind of values using the following function: 

In [21]:
pollution_df.dropna(inplace = True)
pollution_df

State    County           City  Date Local   NO2 Mean  \
0        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
1        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
3        Arizona  Maricopa        Phoenix  2000-01-01  19.041667   
5        Arizona  Maricopa        Phoenix  2000-01-02  22.958333   
7        Arizona  Maricopa        Phoenix  2000-01-02  22.958333   
...          ...       ...            ...         ...        ...   
1746652  Wyoming   Laramie  Not in a city  2016-03-29   2.564706   
1746654  Wyoming   Laramie  Not in a city  2016-03-30   1.083333   
1746656  Wyoming   Laramie  Not in a city  2016-03-30   1.083333   
1746658  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   
1746660  Wyoming   Laramie  Not in a city  2016-03-31   0.939130   

         NO2 1st Max Value  NO2 1st Max Hour  NO2 AQI   O3 Mean  \
0                     49.0                19       46  0.022500   
1                     49.0                19       46  0.022500   
3                     49.0                19       46  0.022500   
5                     36.0                19       34  0.013375   
7                     36.0                19       34  0.013375   
...                    ...               ...      ...       ...   
1746652                3.6                 6        3  0.028000   
1746654                1.6                 9        1  0.043917   
1746656                1.6                 9        1  0.043917   
1746658                1.3                 5        1  0.045263   
1746660                1.3                 5        1  0.045263   

         O3 1st Max Value  O3 1st Max Hour  O3 AQI  SO2 Mean  \
0                   0.040               10      34  3.000000   
1                   0.040               10      34  3.000000   
3                   0.040               10      34  2.975000   
5                   0.032               10      27  1.958333   
7                   0.032               10      27  1.937500   
...                   ...              ...     ...       ...   
1746652             0.040               23      37  0.120000   
1746654             0.048               18      44  0.016667   
1746656             0.048               18      44  0.000000   
1746658             0.047                9      44 -0.022727   
1746660             0.047                9      44  0.000000   

         SO2 1st Max Value  SO2 1st Max Hour    SO2 AQI   CO Mean  \
0                      9.0                21  13.000000  1.145833   
1                      9.0                21  13.000000  0.878947   
3                      6.6                23   7.115945  0.878947   
5                      3.0                22   4.000000  1.066667   
7                      2.6                23   7.115945  1.066667   
...                    ...               ...        ...       ...   
1746652                0.4                 8   7.115945  0.006667   
1746654                0.1                 0   0.000000  0.091667   
1746656                0.0                 2   7.115945  0.091667   
1746658                0.0                 0   0.000000  0.100000   
1746660                0.0                 5   7.115945  0.100000   

         CO 1st Max Value  CO 1st Max Hour  CO AQI  
0                     4.2               21     3.0  
1                     2.2               23    25.0  
3                     2.2               23    25.0  
5                     2.3                0    26.0  
7                     2.3                0    26.0  
...                   ...              ...     ...  
1746652               0.1                0     1.0  
1746654               0.1                2     1.0  
1746656               0.1                2     1.0  
1746658               0.1                0     1.0  
1746660               0.1                0     1.0  

[873339 rows x 20 columns]

In this case, having delete the SO2 AQI column and the CO AQI column, which have lots of null values, do not alterate the structure of the dataset in any way. In fact the Air Quality Index is a marginal column in this analysis.

After having done some structural changes, the dimensions of the DataFrame can be checked as follows: 

In [22]:
pollution_df.shape

(873339, 20)

This function returns a tuple representing the size of the dataset made of 20 columns and 436.876 rows. 

Now it is valuable to check if all the null values are deleted correctly, using again the same code as above:

In [23]:
pollution_df.isnull().sum()

State                0
County               0
City                 0
Date Local           0
NO2 Mean             0
NO2 1st Max Value    0
NO2 1st Max Hour     0
NO2 AQI              0
O3 Mean              0
O3 1st Max Value     0
O3 1st Max Hour      0
O3 AQI               0
SO2 Mean             0
SO2 1st Max Value    0
SO2 1st Max Hour     0
SO2 AQI              0
CO Mean              0
CO 1st Max Value     0
CO 1st Max Hour      0
CO AQI               0
dtype: int64

The code worked correclty. 

3. Show some interesting plots: an essential skill of a data scientist is being able to show the important information by using easily understandable graphs. Use the libraries introduced in class to show case some interesting aspects of the dataset. 
An additional 2 points can be awarded for code cleanliness

In this case, it is important to recall three of the previous libraries that we import at the beginning, such as: 

In [24]:
import matplotlib.pyplot as plt 
import numpy as np 
import pandas as pd 

Since the chosen dataset has lots of data, to show some interesting plots it is better to select just some of the features. For example, the code below only takes into account values that refer to the city of Phoenix. 

In [43]:
pollution_phoenix = pollution_df[pollution_df['City'] == 'Phoenix']
pollution_phoenix

State    County     City  Date Local   NO2 Mean  NO2 1st Max Value  \
0        Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
1        Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
3        Arizona  Maricopa  Phoenix  2000-01-01  19.041667               49.0   
5        Arizona  Maricopa  Phoenix  2000-01-02  22.958333               36.0   
7        Arizona  Maricopa  Phoenix  2000-01-02  22.958333               36.0   
...          ...       ...      ...         ...        ...                ...   
1722960  Arizona  Maricopa  Phoenix  2016-03-24  20.195833               41.0   
1722962  Arizona  Maricopa  Phoenix  2016-03-25  17.308333               40.2   
1722964  Arizona  Maricopa  Phoenix  2016-03-25  17.308333               40.2   
1722966  Arizona  Maricopa  Phoenix  2016-03-26  14.579167               35.2   
1722968  Arizona  Maricopa  Phoenix  2016-03-26  14.579167               35.2   

         NO2 1st Max Hour  NO2 AQI   O3 Mean  O3 1st Max Value  \
0                      19       46  0.022500             0.040   
1                      19       46  0.022500             0.040   
3                      19       46  0.022500             0.040   
5                      19       34  0.013375             0.032   
7                      19       34  0.013375             0.032   
...                   ...      ...       ...               ...   
1722960                21       39  0.022625             0.049   
1722962                22       38  0.027125             0.051   
1722964                22       38  0.027125             0.051   
1722966                 0       33  0.042053             0.060   
1722968                 0       33  0.042053             0.060   

         O3 1st Max Hour  O3 AQI  SO2 Mean  SO2 1st Max Value  \
0                     10      34  3.000000                9.0   
1                     10      34  3.000000                9.0   
3                     10      34  2.975000                6.6   
5                     10      27  1.958333                3.0   
7                     10      27  1.937500                2.6   
...                  ...     ...       ...                ...   
1722960               11      45  0.200000                0.6   
1722962               11      47  0.445833                1.0   
1722964               11      47  0.425000                0.8   
1722966               11      67  0.637500                1.2   
1722968               11      67  0.600000                1.1   

         SO2 1st Max Hour    SO2 AQI   CO Mean  CO 1st Max Value  \
0                      21  13.000000  1.145833               4.2   
1                      21  13.000000  0.878947               2.2   
3                      23   7.115945  0.878947               2.2   
5                      22   4.000000  1.066667               2.3   
7                      23   7.115945  1.066667               2.3   
...                   ...        ...       ...               ...   
1722960                11   7.115945  0.458333               0.6   
1722962                 0   1.000000  0.470833               0.8   
1722964                23   7.115945  0.470833               0.8   
1722966                 0   1.000000  0.454167               0.8   
1722968                 2   7.115945  0.454167               0.8   

         CO 1st Max Hour  CO AQI  
0                     21     3.0  
1                     23    25.0  
3                     23    25.0  
5                      0    26.0  
7                      0    26.0  
...                  ...     ...  
1722960                5     7.0  
1722962                1     9.0  
1722964                1     9.0  
1722966                3     9.0  
1722968                3     9.0  

[18956 rows x 20 columns]

As it can be seen, there is still a lot of data, in fact there are 18.956 rows and 20 columns.

If, for example, it is tried to make a very primitive plot with all the data in the NO2 Mean column, what comes out is: 

In [44]:
plt.figure
plt.plot(pollution_phoenix['NO2 Mean'], label = '')
plt.show()

Looking at the graph, it is very difficult to understand what it wants to communicate due to the fact that there is still too much data. In fact, here the phrase "too much data provides no data" clearly finds meaning. 

An interesting thing that can be done is to filter the data from Phoenix for the year 2001. 

Dealing with the following code it can be said that the first line converts the 'Date Local' column of the pollution_phoenix DataFrame into a 'datetime' object and this operation is useful when working with time data as it allows for specific date operations. The second and the third line create 2 'datetime' objects representing the start date and the end date of the year 2001. The fourth line filters the pollution_phoenix DataFrame keeping only the rows where the local date ('Date Local') is between the start and the end date of 2001. The fifth line groups the data based on the ('Date Local') considering only the date part without the time ('.dt.date') and then calculates the first value ('.first()') of the NO2 Mean column for each day (since there are about 4 measurement for every day).  

In [26]:
pollution_phoenix['Date Local'] = pd.to_datetime(pollution_phoenix['Date Local'])
start_date = pd.to_datetime('2001-01-01')
end_date = pd.to_datetime('2001-12-31')
pollution_phoenix = pollution_phoenix[(pollution_phoenix['Date Local'] >= start_date) & (pollution_phoenix['Date Local'] <= end_date)]
pollution_phoenix_first = pollution_phoenix.groupby(pollution_phoenix['Date Local'].dt.date)['NO2 Mean'].first()
pollution_phoenix_first

/var/folders/nt/j3zdw65j5ys5rx0l1vhss5y40000gn/T/ipykernel_1207/184414100.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  pollution_phoenix['Date Local'] = pd.to_datetime(pollution_phoenix['Date Local'])


Date Local
2001-01-01    36.250000
2001-01-02    36.173913
2001-01-03    36.083333
2001-01-04    43.041667
2001-01-05    42.500000
                ...    
2001-12-27    42.916667
2001-12-28    46.652174
2001-12-29    38.875000
2001-12-30    38.875000
2001-12-31    34.363636
Name: NO2 Mean, Length: 359, dtype: float64

What was expectet is a length of 365, since the year 2001 has 365 days but what emerged is a length of 359. So it is best to check if some measurement are missing or if the previous code is not accurate. 

In this case, the first 4 lines are the same as the previous code, so what's new are the last lines. In particular, the fifth line calculates whether there is at least one measurement for each day of 2001 and it does this by checking if the number of unique dates in the filtered DataFrame pollution_phoenix is equal to the total number of days in 2001, moreover, the '+1' is added to account for both start and end date. The sixth and the following 3 lines refer to the fifth line by printing 'All days in 2001 have at least one measurement' if the equation in line 5 has an output in 'True', while printing 'NOT all days in 2001 have measurement' if the output is 'False'. 

In [27]:
pollution_phoenix['Date Local'] = pd.to_datetime(pollution_phoenix['Date Local'])
start_date = pd.to_datetime('2001-01-01')
end_date = pd.to_datetime('2001-12-31')
pollution_phoenix = pollution_phoenix[(pollution_phoenix['Date Local'] >= start_date) & (pollution_phoenix['Date Local'] <= end_date)]
all_day_measure = len(pollution_phoenix['Date Local'].dt.date.unique()) == (end_date - start_date).days + 1
if all_day_measure:
    print('All days in 2001 have at least one measurement')
else: 
    print('NOT all days in 2001 have measurement')
    

NOT all days in 2001 have measurement


The output of the code is negative, so not every day has been measured in 2001. So what can be said is that the code above is correct. 

In [28]:
#pollution_phoenix['Date Local'] = pd.to_datetime(pollution_phoenix['Date Local'], errors = 'coerce')
#start_date = pd.to_datetime('2001-01-01')
#end_date = pd.to_datetime('2001-12-31')
#pollution_phoenix = pollution_phoenix[(pollution_phoenix['Date Local'] >= start_date) & (pollution_phoenix['Date Local'] <= end_date)]
#days_wit_measurement = len(pollution_phoenix['Date Local']).dt.date.unique()
#print('The number of days in 2001 with at least one measurement is:', days_wit_measurement)

In [29]:
#pollution_phoenix['Date Local'] = pd.to_datetime(pollution_phoenix['Date Local'])
#pollution_phoenix_first = pollution_phoenix.groupby(pollution_phoenix['Date Local'].dt.date)['NO2 Mean'].first().reset_index()
#start_date = pd.to_datetime('2001-01-01')
#end_date = pd.to_datetime('2001-12-31')
#filtered_pollution_phoenix = pollution_phoenix_first.loc[start_date, end_date]
#[(pollution_phoenix_first['Date Local'] >= start_date) & (pollution_phoenix_first['Date Local'] <= end_date)]

#filtered_pollution_phoenix

In [30]:
#pollution_phoenix = pd.date_range(start = '2001-01-01', end = '2001-12-31', freq = 'D')
#pollution_phoenix = pd.DataFrame({'Date Local' : pollution_phoenix})
#pollution_phoenix

In [31]:
#date = {
    #'Date Local': pd.date_range(start = '2001-01-01', end = '2001-12-31', freq = 'D').repeat(4),
    #'NO2 Mean': range(1, 366 * 4 + 1)
#}
#pollution_phoenix = pollution_phoenix.groupby('Date Local').first().reset_index()
#pollution_phoenix

In [32]:
#pollution_phoenix = pollution_phoenix.iloc[np.arange(3, len(pollution_phoenix), 4)]
#pollution_phoenix
#potrei fare la media di ogni pollutants di ogni anno e poi vedere se supera il livello massimo oppure no "consentito"
#potrei vedere la città che in assoluto ha i più alti livelli per ogni pollutants e confrontarlo con il valore più alto di phoenix
 

top = plt.subplot2grid((4,1), (0,0), rowspan = , colspan = )
top.plot(pollution_phoenix.index, pollution_phoenix[''])

bottom = plt.subplot2grid((4,1), (0,0), rowspan = , colspan = )
bottom.plot(pollution_phoenix.index, pollution_phoenix[''])

plt.gcf().set_size_inches(15,8)

In [33]:
pollution_phoenix['NO2 Mean']

91647    36.250000
91649    36.250000
91651    36.173913
91653    36.173913
91655    36.083333
           ...    
93073    38.875000
93075    38.875000
93077    38.875000
93079    34.363636
93081    34.363636
Name: NO2 Mean, Length: 718, dtype: float64

In [34]:
print(len(pollution_phoenix_first))
plt.figure(figsize = (15,8))
plt.plot(pollution_phoenix_first, label = '')
plt.show()
type(pollution_phoenix_first['Date Local'])

359


KeyError: 'Date Local'

In [ ]:
pollution_phoenix = pollution_phoenix.loc[pollution_phoenix['Date Local'] <= '2001-01-01']
print(len(pollution_phoenix))
plt.figure
plt.plot(pollution_phoenix['NO2 Mean'], label = '')
plt.show()
type(pollution_phoenix['Date Local'])

2


pandas.core.series.Series

In [ ]:
pollution_phoenix['O3 Mean']

In [ ]:
pollution_phoenix = pollution_phoenix.loc[pollution_phoenix['Date Local'] <= '2001-01-01']
print(len(pollution_phoenix))
plt.figure
plt.plot(pollution_phoenix['O3 Mean'], label = '')
plt.show()
type(pollution_phoenix['Date Local'])

In [ ]:
pollution_phoenix['SO2 Mean']

In [ ]:
pollution_phoenix = pollution_phoenix.loc[pollution_phoenix['Date Local'] <= '2001-01-01']
print(len(pollution_phoenix))
plt.figure
plt.plot(pollution_phoenix['SO2 Mean'], label = '')
plt.show()
type(pollution_phoenix['Date Local'])

In [ ]:
pollution_phoenix['CO Mean']

In [42]:
plt.figure
plt.plot(pollution_phoenix['CO Mean'], label = '')
plt.show()



A conclusion that can be drawn from these 4 line graphs is that they don't make sense, in fact the problem is that there are too many data and too many data provide no information and so are unuseful. 

In [ ]:
import pandas as pd

In [ ]:
NO2_freq = pollution_phoenix.groupby(['NO2 Mean']).count()
NO2_freq

In [ ]:
O3_freq = pollution_phoenix.groupby(['O3 Mean']).count()
O3_freq

In [ ]:
SO2_freq = pollution_phoenix.groupby(['SO2 Mean']).count()
SO2_freq

In [ ]:
CO_freq = pollution_phoenix.groupby(['CO Mean']).count()
CO_freq

In [ ]:
#per ricreare una tabella che mi interessa phoenix_pollution.pivot_table(phoenix_pollution[:50], values = '', index=['',''])

In [ ]:
#usando phoenix_pollution.groupby(by = ).mean() potrei capire i valori medi di ogni pollutant ? 
#se voglio ordinare di nuovo i valori phoenix_pollution.groupby(by = ).mean().sort_values(by = )

In [ ]:
pollution_phoenix.sort_values(by = 'NO2 Mean') #se voglio fare in ordine decrescente devo aggiungere , ascending = False 
#se voglio passare più colonne, metto (by = [ .....])

In [ ]:
pollution_phoenix.sort_values(by = 'O3 Mean')

In [ ]:
pollution_phoenix.sort_values(by = 'SO2 Mean')

In [ ]:
pollution_phoenix.sort_values(by = 'CO Mean')